name: 'Check'
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: marocchino/tool-versions-action@v1
        id: versions
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.nodejs}}
      - run: yarn
      - run: yarn ci
