name: 'Deploy'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: marocchino/tool-versions-action@v1
        id: versions
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.nodejs}}
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXT_PUBLIC_API_URL: 'https://next-trpc-cloudflare-pages.pages.dev'
      - run: yarn
      - run: npx @cloudflare/next-on-pages --experimental-minify
      - run: node -p -e '`NAME=${require("./package.json").name}`' >> $GITHUB_ENV
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages publish .vercel/output/static --project-name="${{ env.NAME }}" --commit-message "Deploy"
      - run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
