name: 'Deploy'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'
      - run: yarn
      - run: yarn ci
      - run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'
      - uses: pkgdeps/git-tag-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
